name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run docs:build

      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: '.vuepress/dist'
          container_name: "$web"
          connection_string: ${{ secrets.CONNECTION_STRING }}
          sync: true
